apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgresql-tls
  namespace: netbox
spec:
  # Set DNS names to the names of the Postgres hosts
  dnsNames:
    - postgresql
    - postgresql.netbox
    - postgresql.netbox.svc
    - postgresql-r
    - postgresql-r.netbox
    - postgresql-r.netbox.svc
    - postgresql-ro
    - postgresql-ro.netbox
    - postgresql-ro.netbox.svc
    - postgresql-rw
    - postgresql-rw.netbox
    - postgresql-rw.netbox.svc
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: self-signed-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  # Secret names are always required.
  secretName: postgresql-tls
  usages:
    - server auth
